# Generated by Django 6.1 on 2026-09-26 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Tasks",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("description", models.CharField(max_length=250)),
                ("status", models.BooleanField(verbose_name=False)),
                ("date", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
